service: qrcode-service

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region:  ap-northeast-1

package:
 exclude:
   - build_packages.sh
   - Dockerfile
   - requirements.txt

functions:
  qrcode:
    handler: handler.create
    events:
     - http:
         path: qrcode
         method: get
         integration: lambda
         request:
            parameters:
              querystrings:
                text: true
            passThrough: WHEN_NO_TEMPLATES
            template:
              image/png: |
                #define( $loop )
                  {
                  #foreach($key in $map.keySet())
                      #set( $k = $util.escapeJavaScript($key) )
                      #set( $v = $util.escapeJavaScript($map.get($key)).replaceAll("\\'", "'") )
                      "$k":
                        "$v"
                        #if( $foreach.hasNext ) , #end
                  #end
                  }
                #end

                {
                    #set( $map = $input.params().querystring )
                    "query": $loop
                }
